### PR TITLE
Move free to the proper scope to fix #57

### LINKED ISSUE #57: wpantund.cpp fails to compile due to free() out of scope
```
wpantund.cpp: In function 'void signal_critical(int, siginfo_t*, void*)':
wpantund.cpp:296:7: error: 'stack_symbols' was not declared in this scope
  free(stack_symbols);
       ^
Makefile:752: recipe for target 'wpantund-wpantund.o' failed
```

I will submit a PR addressing this issue.

### PR DESCRIPTION
**Pull request by pszkotak**
This PR fixes #57

### CODE REVIEW

**Comment by darconeous** [comment]
The OS X build failure was spurious (Tracked by #61). Will go ahead and merge.
